/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DealerPortalRouteImport } from './routes/dealer-portal'
import { Route as DealerRouteImport } from './routes/dealer'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BookRouteImport } from './routes/book'
import { Route as BecomePartnerRouteImport } from './routes/become-partner'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerPortalRoute = DealerPortalRouteImport.update({
  id: '/dealer-portal',
  path: '/dealer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerRoute = DealerRouteImport.update({
  id: '/dealer',
  path: '/dealer',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomePartnerRoute = BecomePartnerRouteImport.update({
  id: '/become-partner',
  path: '/become-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-partner': typeof BecomePartnerRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/dealer': typeof DealerRoute
  '/dealer-portal': typeof DealerPortalRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/quote': typeof QuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-partner': typeof BecomePartnerRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/dealer': typeof DealerRoute
  '/dealer-portal': typeof DealerPortalRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/quote': typeof QuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/become-partner': typeof BecomePartnerRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/dealer': typeof DealerRoute
  '/dealer-portal': typeof DealerPortalRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/quote': typeof QuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/become-partner'
    | '/book'
    | '/cart'
    | '/dealer'
    | '/dealer-portal'
    | '/login'
    | '/partner'
    | '/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/become-partner'
    | '/book'
    | '/cart'
    | '/dealer'
    | '/dealer-portal'
    | '/login'
    | '/partner'
    | '/quote'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/become-partner'
    | '/book'
    | '/cart'
    | '/dealer'
    | '/dealer-portal'
    | '/login'
    | '/partner'
    | '/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BecomePartnerRoute: typeof BecomePartnerRoute
  BookRoute: typeof BookRoute
  CartRoute: typeof CartRoute
  DealerRoute: typeof DealerRoute
  DealerPortalRoute: typeof DealerPortalRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  QuoteRoute: typeof QuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-portal': {
      id: '/dealer-portal'
      path: '/dealer-portal'
      fullPath: '/dealer-portal'
      preLoaderRoute: typeof DealerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer': {
      id: '/dealer'
      path: '/dealer'
      fullPath: '/dealer'
      preLoaderRoute: typeof DealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-partner': {
      id: '/become-partner'
      path: '/become-partner'
      fullPath: '/become-partner'
      preLoaderRoute: typeof BecomePartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BecomePartnerRoute: BecomePartnerRoute,
  BookRoute: BookRoute,
  CartRoute: CartRoute,
  DealerRoute: DealerRoute,
  DealerPortalRoute: DealerPortalRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  QuoteRoute: QuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
